/// Generated by AssetsRefGenerator on 2022/02/08
class Res {
  static const String address = "assets/Images/address.png";
  static const String badge = "assets/Images/badge.png";
  static const String location = "assets/Images/location.png";
  static const String orders = "assets/Images/orders.png";
  static const String questionicon = "assets/Images/questionicon.png";
  static const String referalperson = "assets/Images/referalperson.png";
  static const String shoppingbag = "assets/Images/shoppingbag.png";
  static const String transparentLogo = "assets/Images/transparentLogo.png";
  static const String wallet = "assets/Images/wallet.png";
  static const String walletupdated = "assets/Images/walletupdated.png";
}
